[package]
name = "program-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
ogl33 = {version = "0.2.0", optional = true}
ash = {version = "0.37.3+1.3.251", optional = true}
ash-window = {version ="0.12.0", optional = true}
shaderc = {version = "0.8", optional = true}
opengles = {version = "0.1.2", optional = true}
sdl2 = { version = "*"}
winit = { version = "0.28.6"}
raw-window-handle = "0.5"
imagine = "0.0.5"
once_cell = "1.17.0"
glsl-include = "0.3"

[features]
vulkan = ["dep:ash", "dep:shaderc", "dep:ash-window", "sdl2/raw-window-handle"]
opengl = ["dep:ogl33"]
gles = ["dep:opengles"]